"""
query.py

Query pipeline for the RAG Q&A bot.

Responsibilities:
    1. Load the existing (already-ingested) ChromaDB collection
    2. Embed the user's question (as a query, not a document)
    3. Retrieve the top-k most relevant chunks
    4. Build a strict, grounded prompt with labeled source citations
    5. Call Gemini to generate an answer using ONLY that retrieved context
    6. Return the answer, the citations used, and the raw retrieved context

This is intentionally separate from ingest.py: ingestion is slow/costly
and run rarely (only when documents change), while querying is fast and
run on every user question. main.py (Phase 4) calls into this module.

Run a one-off question directly from the project root:
    python -m src.query "What is the meal allowance for travel?"
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field

from dotenv import load_dotenv

import chromadb
from chromadb import Documents, EmbeddingFunction, Embeddings
from google import genai
from google.genai import types

from src import config

load_dotenv()


# ==========================================================================
# Result type
# ==========================================================================

@dataclass
class QueryResult:
    """
    Structured result of a single query through the RAG pipeline.

    Attributes:
        answer: The grounded answer text generated by Gemini (or the
            standard refusal message if context was insufficient).
        citations: List of human-readable citation strings, e.g.
            "Source: report.pdf, Page: 4" — one per retrieved chunk,
            in the same order they were given to the model.
        raw_context: The raw retrieved chunk texts, for callers (like a
            CLI "show sources" option) that want the underlying text
            rather than just the citation label.
        retrieved_count: Number of chunks actually retrieved. Useful for
            callers to detect "the database is empty" (0 retrieved).
    """
    answer: str
    citations: list[str] = field(default_factory=list)
    raw_context: list[str] = field(default_factory=list)
    retrieved_count: int = 0


# ==========================================================================
# Step 1: Gemini embedding function for QUERIES (mirrors ingest.py's,
# but tagged with task_type="RETRIEVAL_QUERY" instead of
# "RETRIEVAL_DOCUMENT" -- Gemini's embedding model is trained to align
# these two task types for retrieval, so using the matching one on each
# side measurably improves retrieval quality vs. using the same task
# type for both.)
# ==========================================================================

class GeminiQueryEmbeddingFunction(EmbeddingFunction):
    """
    A ChromaDB-compatible embedding function for embedding the user's
    *query* text, as opposed to the documents being stored.

    IMPORTANT: This must use the exact same model name and
    output_dimensionality as the embedding function used during
    ingestion (see ingest.py's GeminiEmbeddingFunction), or the
    resulting vectors will have mismatched dimensions and similarity
    search will fail/error. Both read from the same config constants
    to guarantee this stays in sync.
    """

    def __init__(
        self,
        client: genai.Client,
        model_name: str = config.EMBEDDING_MODEL,
        output_dimensionality: int = config.EMBEDDING_OUTPUT_DIMENSIONALITY,
    ):
        self._client = client
        self._model_name = model_name
        self._output_dimensionality = output_dimensionality

    def __call__(self, input: Documents) -> Embeddings:
        result = self._client.models.embed_content(
            model=self._model_name,
            contents=input,
            config=types.EmbedContentConfig(
                task_type="RETRIEVAL_QUERY",
                output_dimensionality=self._output_dimensionality,
            ),
        )
        return [embedding.values for embedding in result.embeddings]

    def name(self) -> str:
        return "gemini-embedding-001-query"


# ==========================================================================
# Step 2: Load the persisted collection
# ==========================================================================

def load_collection(client: genai.Client, db_dir=None):
    """
    Loads the existing ChromaDB collection created by ingest.py.

    Args:
        client: An initialized google-genai Client (for the embedding
            function ChromaDB will use internally during .query()).
        db_dir: Override for the ChromaDB persistence folder
            (defaults to config.DB_DIR).

    Returns:
        The ChromaDB collection object.

    Raises:
        RuntimeError: If the database directory or collection doesn't
            exist yet (i.e. ingestion hasn't been run), with a message
            telling the user how to fix it.
    """
    db_dir = db_dir or config.DB_DIR

    if not db_dir.exists():
        raise RuntimeError(
            f"No database found at '{db_dir}'. "
            f"Run ingestion first: python -m src.ingest"
        )

    chroma_client = chromadb.PersistentClient(path=str(db_dir))
    embedding_fn = GeminiQueryEmbeddingFunction(client=client)

    try:
        collection = chroma_client.get_collection(
            name=config.COLLECTION_NAME,
            embedding_function=embedding_fn,
        )
    except Exception as e:
        raise RuntimeError(
            f"Could not load collection '{config.COLLECTION_NAME}' from '{db_dir}': {e}\n"
            f"Run ingestion first: python -m src.ingest"
        )

    return collection


# ==========================================================================
# Step 3: Retrieval
# ==========================================================================

def retrieve_chunks(collection, user_query: str, top_k: int = config.TOP_K) -> dict:
    """
    Embeds the query and retrieves the top-k most relevant chunks.

    Args:
        collection: A loaded ChromaDB collection (see load_collection).
        user_query: The user's natural-language question.
        top_k: Number of chunks to retrieve.

    Returns:
        ChromaDB's raw query() result dict, containing parallel lists
        under "documents", "metadatas", and "distances" (each wrapped
        in an outer list because ChromaDB supports batched queries —
        we only ever send one query, so we index [0] when consuming this).
    """
    results = collection.query(
        query_texts=[user_query],
        n_results=top_k,
    )
    return results


# ==========================================================================
# Step 4: Prompt construction (strict grounding)
# ==========================================================================

def build_grounded_prompt(user_query: str, documents: list[str], metadatas: list[dict]) -> str:
    """
    Builds the full prompt sent to Gemini: a strict system instruction
    plus the retrieved context blocks (each labeled with its source
    file and page/block number) plus the user's question.

    Args:
        user_query: The user's question.
        documents: Retrieved chunk texts, in relevance order.
        metadatas: Parallel list of metadata dicts for each chunk
            (each containing at least "source" and "page").

    Returns:
        The complete prompt string ready to send to the generation model.
    """
    system_instruction = (
        "You are a precise, professional document Q&A assistant. "
        "Answer the user's question using ONLY the context provided below — "
        "never use your own outside knowledge, even if you happen to know the "
        "answer. "
        "Cite your sources inline next to every fact you state, using the "
        "format (filename, Page X). "
        f"If the answer cannot be found in the provided context, respond with "
        f"EXACTLY this sentence and nothing else: \"{config.NO_ANSWER_MESSAGE}\""
    )

    context_blocks = []
    for doc, meta in zip(documents, metadatas):
        source = meta.get("source", "unknown")
        page = meta.get("page", "unknown")
        context_blocks.append(f"[Source: {source}, Page: {page}]\n{doc}")

    context_payload = "\n\n---\n\n".join(context_blocks) if context_blocks else "(no context retrieved)"

    prompt = (
        f"{system_instruction}\n\n"
        f"CONTEXT:\n{context_payload}\n\n"
        f"QUESTION: {user_query}\n\n"
        f"ANSWER:"
    )
    return prompt


def build_citations(metadatas: list[dict]) -> list[str]:
    """
    Converts retrieved chunk metadata into human-readable citation strings.

    Args:
        metadatas: List of metadata dicts, each with "source" and "page".

    Returns:
        List of strings like "Source: report.pdf, Page: 4", de-duplicated
        while preserving first-seen order (a document can contribute
        multiple chunks; we don't want the same citation repeated).
    """
    seen = set()
    citations = []
    for meta in metadatas:
        source = meta.get("source", "unknown")
        page = meta.get("page", "unknown")
        label = f"Source: {source}, Page: {page}"
        if label not in seen:
            seen.add(label)
            citations.append(label)
    return citations


# ==========================================================================
# Step 5: Generation
# ==========================================================================

def generate_answer(client: genai.Client, prompt: str) -> str:
    """
    Sends the grounded prompt to the Gemini generation model and
    returns the answer text.

    Args:
        client: An initialized google-genai Client.
        prompt: The full grounded prompt (see build_grounded_prompt).

    Returns:
        The model's answer text. Falls back to the standard
        NO_ANSWER_MESSAGE if the API call fails outright (e.g. network
        issue), so the CLI never crashes on a transient error -- it
        degrades to "I don't know" instead.
    """
    try:
        response = client.models.generate_content(
            model=config.GENERATION_MODEL,
            contents=prompt,
        )
        text = (response.text or "").strip()
        return text if text else config.NO_ANSWER_MESSAGE
    except Exception as e:
        print(f"[ERROR] Gemini generation call failed: {e}", file=sys.stderr)
        return config.NO_ANSWER_MESSAGE


# ==========================================================================
# Step 6: Orchestration — the full query pipeline
# ==========================================================================

def query_rag_pipeline(
    user_query: str,
    client: genai.Client | None = None,
    top_k: int = config.TOP_K,
) -> QueryResult:
    """
    Runs the full query pipeline end to end: load DB -> retrieve ->
    build prompt -> generate -> return structured result.

    Args:
        user_query: The user's natural-language question.
        client: An optional pre-built google-genai Client. If not
            provided, one is created using the API key from .env
            (convenient for one-off calls; main.py should create a
            single client once and reuse it across questions instead,
            to avoid re-authenticating on every question).
        top_k: Number of chunks to retrieve.

    Returns:
        A QueryResult with the answer, citations, raw context, and
        retrieved chunk count.

    Raises:
        EnvironmentError: If no API key is available and none was
            supplied via `client`.
        RuntimeError: If the vector database hasn't been built yet
            (ingestion was never run).
    """
    if client is None:
        api_key = config.get_api_key()
        client = genai.Client(api_key=api_key)

    collection = load_collection(client)

    if collection.count() == 0:
        return QueryResult(
            answer=config.NO_ANSWER_MESSAGE,
            citations=[],
            raw_context=[],
            retrieved_count=0,
        )

    results = retrieve_chunks(collection, user_query, top_k=top_k)
    documents = results["documents"][0]
    metadatas = results["metadatas"][0]

    if not documents:
        return QueryResult(
            answer=config.NO_ANSWER_MESSAGE,
            citations=[],
            raw_context=[],
            retrieved_count=0,
        )

    prompt = build_grounded_prompt(user_query, documents, metadatas)
    answer = generate_answer(client, prompt)
    citations = build_citations(metadatas)

    return QueryResult(
        answer=answer,
        citations=citations,
        raw_context=documents,
        retrieved_count=len(documents),
    )


# ==========================================================================
# Standalone CLI entry point for quick one-off testing
# ==========================================================================

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python -m src.query \"your question here\"")
        sys.exit(1)

    question = " ".join(sys.argv[1:])

    try:
        result = query_rag_pipeline(question)
    except (EnvironmentError, RuntimeError) as e:
        print(f"[ERROR] {e}")
        sys.exit(1)

    print("\n--- ANSWER ---")
    print(result.answer)

    print("\n--- CITATIONS ---")
    if result.citations:
        for c in result.citations:
            print(f"  - {c}")
    else:
        print("  (none)")
